updateBranch: true
deleteBranchAfterMerge: true
reportStatus: true

minApprovals:
  COLLABORATOR: 0
maxRequestedChanges:
  NONE: 0
blockingTitleRegex: '^Bump @angular'

rules:
- minApprovals:
    OWNER: 1
- requiredLabels:
  - dependencies
