version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: America/New_York
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.1101.3
    - 0.1101.4
    - 0.1102.0
    - 0.1102.1
    - 0.1102.10
    - 0.1102.11
    - 0.1102.2
    - 0.1102.3
    - 0.1102.4
    - 0.1102.5
    - 0.1102.6
    - 0.1102.7
    - 0.1102.8
    - 0.1102.9
  - dependency-name: "@angular/cli"
    versions:
    - 11.1.3
    - 11.1.4
    - 11.2.0
    - 11.2.1
    - 11.2.10
    - 11.2.11
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.5
    - 3.6.8
  - dependency-name: rxjs
    versions:
    - 6.6.6
  - dependency-name: ng-packagr
    versions:
    - 11.1.2
    - 11.1.3
    - 11.2.3
  - dependency-name: typescript
    versions:
    - 4.1.4
