version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'daily'
      time: '03:00'
      timezone: 'America/New_York'
    versioning-strategy: increase
    open-pull-requests-limit: 10
    labels:
      - dependencies
    ignore:
      - dependency-name: '@angular*'
      - dependency-name: 'ng-packagr'
    groups:
      typescript and eslint:
        patterns:
          - '*typescript*'
          - '*eslint*'
      jest:
        patterns:
          - '*jest*'
      types:
        patterns:
          - '@types/*'
        exclude-patterns:
          - '*jest*'
