name: "Update Angular"

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      
      - uses: tinesoft/ngx-uptodate@v1.1
        with:
          repo-token: ${{ secrets.GH_TOKEN }}
